app = "lead-funnel-worker"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NUDGE_INTERVAL_MINUTES = "240"
  DB_PATH = "/data/leads.db"

[[mounts]]
  source = "lead_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]